services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    container_name: tcr_app
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "3000:80"
    environment:
      WORDPRESS_DB_HOST: tcr_db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: cnp_
      WORDPRESS_REDIS_HOST: tcr_redis
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
        define('WP_MEMORY_LIMIT', '512M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
    volumes:
      - ../:/var/www/html
      - ./php-conf/zzz-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
    networks:
      - wp_network

  redis:
    image: redis:7-alpine
    container_name: tcr_redis
    restart: unless-stopped
    command: >
      redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --save 60 1000 --save 300 100 --loglevel warning --tcp-keepalive 60 --timeout 300
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wp_network

volumes:
  redis_data:

networks:
  wp_network:
    external: true
    name: wordpress_default
