FROM wordpress:php8.3-apache

# Install PHP Redis extension
RUN pecl install redis \
    && docker-php-ext-enable redis

# Install WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

# Verify installation
RUN php -m | grep redis

